### ISSUE TITLE
ssh-import-id

### ISSUE THREAD

**Issue by ebal** [hartwork/image-bootstrap#131]
Hi,

this is more a discussion/question than an issue. 

To automatically import users ssh keys from github/gitlab into arch, we need **ssh-import-id**. Unfortunately there is no official package, but exist as pip. Below are my personal notes on cloud-init configuration (user-data,yml).

```yaml
#cloud-config

unverified_modules: ["ssh-import-id"]
...
users:
  - name: ebal
    ssh_import_id:
      - gh:ebal
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
...

bootcmd:
  - echo " ========= EBAL BOOTCMD =========="
  - pacman -Sq archlinux-keyring
  - sleep 20
  - pacman -Sq --noconfirm python-pip
  - pip install ssh-import-id
...
```

as ssh-import-id is not an official module, we need to "unverify" it and the problem with archlinux-keyring is that it takes a bit time to initial (download gpg keys) so to install pip we need to wait. 

It would be great to have ssh-import-id to the qcow2 image but perhaps my way is not the most efficient to do.

What do you think ? 
Is there a better way to have ssh-import-key ? 

thanks in advance
